import { digitalJunkDrawerTranslations } from "./digitalJunkDrawerTranslations.js";

export const languages = [
  ["en", "EN", "English"],
  ["pt-BR", "PT", "Português"],
  ["es", "ES", "Español"],
  ["fr", "FR", "Français"],
  ["de", "DE", "Deutsch"],
  ["zh-CN", "中文", "中文"],
  ["hi", "HI", "हिन्दी"],
  ["ar", "AR", "العربية"],
];

export const rtlLanguages = new Set(["ar"]);

const easterEggTranslations = {
  en: {
    common: { achievementUnlocked: "Achievement unlocked: {achievement}" },
    achievements: {
      digitalExplorer: { name: "Digital Explorer", description: "You discovered something that was not in the menu." },
      bugHunter: { name: "Bug Hunter", description: "You tracked down an unstable object on the lost page." },
    },
    lab: { title: "MEDIATRIX LAB", accessGranted: "> access granted", lead: "Experimental digital solutions.", congratulations: "Congratulations! Your curiosity unlocked this secret area.", storyPrompt: "The key is in the footer! Capture the discovery and share it in your Story.", close: "Close" },
    modal: { eyebrow: "Achievement unlocked", close: "Close the {achievement} achievement dialog" },
    share: {
      regionLabel: "Share the {achievement} achievement", shareAria: "Share the {achievement} achievement on an Instagram Story",
      creating: "Creating Story…", shareButton: "Share to Instagram Story", copyAria: "Copy the suggested Instagram Story text", copied: "Copied!", copyButton: "Copy Story text",
      note: "Choose Instagram from your device’s sharing menu and complete the Story manually.", assetUnavailable: "The Story image is temporarily unavailable. Please try again.",
      copySuccess: "Story text copied.", copyFailure: "We couldn’t copy the Story text automatically. Please try again.", shareCompleted: "Your device completed the share action. You still control whether the Story is published.",
      shareCanceled: "Sharing canceled. Nothing was published automatically.", createFailure: "We couldn’t create the Story image. Please try again.",
      fallbackInstructions: "Story image saved. Open Instagram, create a new Story, select the image, and mention @mediatrixtech.",
      fallbackCopyFailure: "The Story text could not be copied automatically. Use “Copy Story text” above.", instagramAria: "Open @mediatrixtech on Instagram in a new tab", openInstagram: "Open @mediatrixtech",
      dialogTitle: "Mediatrix Tech — {achievement}",
    },
    story: { discovery: "I discovered a secret on the Mediatrix Tech website!", question: "Can you find it too?", achievementUnlocked: "ACHIEVEMENT UNLOCKED", secretFound: "> SECRET FOUND_", tagline: "Create. Connect. Convert." },
    notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Mediatrix Tech homepage", code: "HTTP / LOST_SIGNAL", message: "This page escaped into another dimension.", returnHome: "Return to homepage", objectAria: "Interactive code object. Activate five times to investigate.", objectHint: "unstable object" },
    console: "You opened the console. Good.\nCurious people build better things.\nCreate. Connect. Convert.",
  },
  "pt-BR": {
    common: { achievementUnlocked: "Conquista desbloqueada: {achievement}" },
    achievements: { digitalExplorer: { name: "Explorador Digital", description: "Você descobriu algo que não estava no menu." }, bugHunter: { name: "Caçador de Bugs", description: "Você encontrou um objeto instável na página perdida." } },
    lab: { title: "LABORATÓRIO MEDIATRIX", accessGranted: "> acesso concedido", lead: "Soluções digitais experimentais.", congratulations: "Parabéns! Sua curiosidade desbloqueou esta área secreta.", storyPrompt: "A chave está no rodapé! Registre a descoberta e compartilhe no seu Story.", close: "Fechar" },
    modal: { eyebrow: "Conquista desbloqueada", close: "Fechar a conquista {achievement}" },
    share: { regionLabel: "Compartilhar a conquista {achievement}", shareAria: "Compartilhar a conquista {achievement} em um Story do Instagram", creating: "Criando Story…", shareButton: "Compartilhar no Story do Instagram", copyAria: "Copiar o texto sugerido para o Story do Instagram", copied: "Copiado!", copyButton: "Copiar texto do Story", note: "Escolha o Instagram no menu de compartilhamento do dispositivo e conclua o Story manualmente.", assetUnavailable: "A imagem do Story está temporariamente indisponível. Tente novamente.", copySuccess: "Texto do Story copiado.", copyFailure: "Não foi possível copiar o texto do Story automaticamente. Tente novamente.", shareCompleted: "Seu dispositivo concluiu a ação de compartilhamento. A publicação do Story continua sob seu controle.", shareCanceled: "Compartilhamento cancelado. Nada foi publicado automaticamente.", createFailure: "Não foi possível criar a imagem do Story. Tente novamente.", fallbackInstructions: "Imagem do Story salva. Abra o Instagram, crie um novo Story, selecione a imagem e adicione @mediatrixtech como menção.", fallbackCopyFailure: "O texto do Story não pôde ser copiado automaticamente. Use “Copiar texto do Story” acima.", instagramAria: "Abrir @mediatrixtech no Instagram em uma nova aba", openInstagram: "Abrir @mediatrixtech", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "Descobri um segredo no site da Mediatrix Tech!", question: "Você também consegue encontrá-lo?", achievementUnlocked: "CONQUISTA DESBLOQUEADA", secretFound: "> SEGREDO ENCONTRADO_", tagline: "Crie. Conecte. Converta." },
    notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Página inicial da Mediatrix Tech", code: "HTTP / SINAL_PERDIDO", message: "Esta página escapou para outra dimensão.", returnHome: "Voltar à página inicial", objectAria: "Objeto de código interativo. Ative cinco vezes para investigar.", objectHint: "objeto instável" },
    console: "Você abriu o console. Ótimo.\nPessoas curiosas criam coisas melhores.\nCrie. Conecte. Converta.",
  },
  es: {
    common: { achievementUnlocked: "Logro desbloqueado: {achievement}" }, achievements: { digitalExplorer: { name: "Explorador digital", description: "Descubriste algo que no estaba en el menú." }, bugHunter: { name: "Cazador de bugs", description: "Encontraste un objeto inestable en la página perdida." } },
    lab: { title: "LABORATORIO MEDIATRIX", accessGranted: "> acceso concedido", lead: "Soluciones digitales experimentales.", congratulations: "¡Enhorabuena! Tu curiosidad desbloqueó esta área secreta.", storyPrompt: "¡La clave está en el pie de página! Captura el descubrimiento y compártelo en tu historia.", close: "Cerrar" }, modal: { eyebrow: "Logro desbloqueado", close: "Cerrar el logro {achievement}" },
    share: { regionLabel: "Compartir el logro {achievement}", shareAria: "Compartir el logro {achievement} en una historia de Instagram", creating: "Creando historia…", shareButton: "Compartir en una historia de Instagram", copyAria: "Copiar el texto sugerido para la historia de Instagram", copied: "¡Copiado!", copyButton: "Copiar texto de la historia", note: "Elige Instagram en el menú para compartir de tu dispositivo y completa la historia manualmente.", assetUnavailable: "La imagen de la historia no está disponible temporalmente. Inténtalo de nuevo.", copySuccess: "Texto de la historia copiado.", copyFailure: "No pudimos copiar automáticamente el texto de la historia. Inténtalo de nuevo.", shareCompleted: "Tu dispositivo completó la acción de compartir. Tú decides si publicas la historia.", shareCanceled: "Se canceló la acción de compartir. No se publicó nada automáticamente.", createFailure: "No pudimos crear la imagen de la historia. Inténtalo de nuevo.", fallbackInstructions: "Imagen de la historia guardada. Abre Instagram, crea una historia nueva, selecciona la imagen y añade @mediatrixtech como mención.", fallbackCopyFailure: "El texto de la historia no pudo copiarse automáticamente. Usa «Copiar texto de la historia» arriba.", instagramAria: "Abrir @mediatrixtech en Instagram en una pestaña nueva", openInstagram: "Abrir @mediatrixtech", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "¡Descubrí un secreto en el sitio web de Mediatrix Tech!", question: "¿Tú también puedes encontrarlo?", achievementUnlocked: "LOGRO DESBLOQUEADO", secretFound: "> SECRETO ENCONTRADO_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Página de inicio de Mediatrix Tech", code: "HTTP / SEÑAL_PERDIDA", message: "Esta página escapó a otra dimensión.", returnHome: "Volver al inicio", objectAria: "Objeto de código interactivo. Actívalo cinco veces para investigar.", objectHint: "objeto inestable" }, console: "Abriste la consola. Bien.\nLas personas curiosas crean cosas mejores.\nCrea. Conecta. Convierte.",
  },
  fr: {
    common: { achievementUnlocked: "Succès débloqué : {achievement}" }, achievements: { digitalExplorer: { name: "Explorateur numérique", description: "Vous avez découvert quelque chose qui ne figurait pas dans le menu." }, bugHunter: { name: "Chasseur de bugs", description: "Vous avez repéré un objet instable sur la page perdue." } }, lab: { title: "LABORATOIRE MEDIATRIX", accessGranted: "> accès autorisé", lead: "Solutions numériques expérimentales.", congratulations: "Félicitations ! Votre curiosité a débloqué cette zone secrète.", storyPrompt: "La clé se trouve dans le pied de page ! Immortalisez votre découverte et partagez-la dans votre story.", close: "Fermer" }, modal: { eyebrow: "Succès débloqué", close: "Fermer le succès {achievement}" },
    share: { regionLabel: "Partager le succès {achievement}", shareAria: "Partager le succès {achievement} dans une story Instagram", creating: "Création de la story…", shareButton: "Partager dans une story Instagram", copyAria: "Copier le texte suggéré pour la story Instagram", copied: "Copié !", copyButton: "Copier le texte de la story", note: "Choisissez Instagram dans le menu de partage de votre appareil et terminez la story manuellement.", assetUnavailable: "L’image de la story est temporairement indisponible. Réessayez.", copySuccess: "Texte de la story copié.", copyFailure: "Impossible de copier automatiquement le texte de la story. Réessayez.", shareCompleted: "Votre appareil a terminé l’action de partage. Vous gardez le contrôle de la publication.", shareCanceled: "Partage annulé. Rien n’a été publié automatiquement.", createFailure: "Impossible de créer l’image de la story. Réessayez.", fallbackInstructions: "Image de la story enregistrée. Ouvrez Instagram, créez une nouvelle story, sélectionnez l’image et ajoutez la mention @mediatrixtech.", fallbackCopyFailure: "Le texte de la story n’a pas pu être copié automatiquement. Utilisez « Copier le texte de la story » ci-dessus.", instagramAria: "Ouvrir @mediatrixtech sur Instagram dans un nouvel onglet", openInstagram: "Ouvrir @mediatrixtech", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "J’ai découvert un secret sur le site Mediatrix Tech !", question: "Saurez-vous le trouver aussi ?", achievementUnlocked: "SUCCÈS DÉBLOQUÉ", secretFound: "> SECRET TROUVÉ_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Accueil de Mediatrix Tech", code: "HTTP / SIGNAL_PERDU", message: "Cette page s’est échappée dans une autre dimension.", returnHome: "Retour à l’accueil", objectAria: "Objet de code interactif. Activez-le cinq fois pour enquêter.", objectHint: "objet instable" }, console: "Vous avez ouvert la console. Bien.\nLes personnes curieuses créent de meilleures choses.\nCréez. Connectez. Convertissez.",
  },
  de: {
    common: { achievementUnlocked: "Erfolg freigeschaltet: {achievement}" }, achievements: { digitalExplorer: { name: "Digitaler Entdecker", description: "Sie haben etwas entdeckt, das nicht im Menü stand." }, bugHunter: { name: "Bug-Jäger", description: "Sie haben auf der verlorenen Seite ein instabiles Objekt aufgespürt." } }, lab: { title: "MEDIATRIX LABOR", accessGranted: "> Zugriff gewährt", lead: "Experimentelle digitale Lösungen.", congratulations: "Glückwunsch! Ihre Neugier hat diesen geheimen Bereich freigeschaltet.", storyPrompt: "Der Schlüssel befindet sich in der Fußzeile! Halten Sie die Entdeckung fest und teilen Sie sie in Ihrer Story.", close: "Schließen" }, modal: { eyebrow: "Erfolg freigeschaltet", close: "Erfolg {achievement} schließen" },
    share: { regionLabel: "Erfolg {achievement} teilen", shareAria: "Erfolg {achievement} in einer Instagram-Story teilen", creating: "Story wird erstellt…", shareButton: "In Instagram-Story teilen", copyAria: "Vorgeschlagenen Instagram-Story-Text kopieren", copied: "Kopiert!", copyButton: "Story-Text kopieren", note: "Wählen Sie Instagram im Teilen-Menü Ihres Geräts und stellen Sie die Story manuell fertig.", assetUnavailable: "Das Story-Bild ist vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.", copySuccess: "Story-Text kopiert.", copyFailure: "Der Story-Text konnte nicht automatisch kopiert werden. Bitte versuchen Sie es erneut.", shareCompleted: "Ihr Gerät hat den Teilen-Vorgang abgeschlossen. Sie entscheiden, ob die Story veröffentlicht wird.", shareCanceled: "Teilen abgebrochen. Es wurde nichts automatisch veröffentlicht.", createFailure: "Das Story-Bild konnte nicht erstellt werden. Bitte versuchen Sie es erneut.", fallbackInstructions: "Story-Bild gespeichert. Öffnen Sie Instagram, erstellen Sie eine neue Story, wählen Sie das Bild und erwähnen Sie @mediatrixtech.", fallbackCopyFailure: "Der Story-Text konnte nicht automatisch kopiert werden. Verwenden Sie oben „Story-Text kopieren“.", instagramAria: "@mediatrixtech auf Instagram in einem neuen Tab öffnen", openInstagram: "@mediatrixtech öffnen", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "Ich habe ein Geheimnis auf der Mediatrix Tech Website entdeckt!", question: "Können Sie es auch finden?", achievementUnlocked: "ERFOLG FREIGESCHALTET", secretFound: "> GEHEIMNIS GEFUNDEN_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Startseite von Mediatrix Tech", code: "HTTP / SIGNAL_VERLOREN", message: "Diese Seite ist in eine andere Dimension entkommen.", returnHome: "Zurück zur Startseite", objectAria: "Interaktives Codeobjekt. Fünfmal aktivieren, um es zu untersuchen.", objectHint: "instabiles Objekt" }, console: "Sie haben die Konsole geöffnet. Gut.\nNeugierige Menschen erschaffen bessere Dinge.\nGestalten. Verbinden. Konvertieren.",
  },
  "zh-CN": {
    common: { achievementUnlocked: "已解锁成就：{achievement}" }, achievements: { digitalExplorer: { name: "数字探索者", description: "你发现了一个菜单中没有的内容。" }, bugHunter: { name: "漏洞猎人", description: "你在迷失页面找到了一个不稳定对象。" } }, lab: { title: "MEDIATRIX 实验室", accessGranted: "> 已获准访问", lead: "实验性数字解决方案。", congratulations: "恭喜！你的好奇心解锁了这个秘密区域。", storyPrompt: "钥匙就在页脚！记录这次发现并分享到你的 Instagram 快拍。", close: "关闭" }, modal: { eyebrow: "成就已解锁", close: "关闭“{achievement}”成就" },
    share: { regionLabel: "分享“{achievement}”成就", shareAria: "在 Instagram 快拍中分享“{achievement}”成就", creating: "正在创建快拍…", shareButton: "分享到 Instagram 快拍", copyAria: "复制建议的 Instagram 快拍文字", copied: "已复制！", copyButton: "复制快拍文字", note: "请从设备的分享菜单中选择 Instagram，并手动完成快拍。", assetUnavailable: "快拍图片暂时不可用，请重试。", copySuccess: "快拍文字已复制。", copyFailure: "无法自动复制快拍文字，请重试。", shareCompleted: "你的设备已完成分享操作，是否发布快拍仍由你决定。", shareCanceled: "已取消分享，未自动发布任何内容。", createFailure: "无法创建快拍图片，请重试。", fallbackInstructions: "快拍图片已保存。请打开 Instagram，创建新快拍，选择图片并添加 @mediatrixtech 提及。", fallbackCopyFailure: "无法自动复制快拍文字，请使用上方的“复制快拍文字”。", instagramAria: "在新标签页中打开 Instagram 上的 @mediatrixtech", openInstagram: "打开 @mediatrixtech", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "我在 Mediatrix Tech 网站发现了一个隐藏彩蛋！", question: "你也能找到它吗？", achievementUnlocked: "成就已解锁", secretFound: "> 已发现秘密_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Mediatrix Tech 首页", code: "HTTP / 信号丢失", message: "这个页面逃到了另一个维度。", returnHome: "返回首页", objectAria: "交互式代码对象。连续激活五次即可调查。", objectHint: "不稳定对象" }, console: "你打开了控制台。很好。\n好奇的人会创造更好的作品。\n创造。连接。转化。",
  },
  hi: {
    common: { achievementUnlocked: "उपलब्धि अनलॉक हुई: {achievement}" }, achievements: { digitalExplorer: { name: "डिजिटल खोजकर्ता", description: "आपने कुछ ऐसा खोजा जो मेन्यू में नहीं था।" }, bugHunter: { name: "बग हंटर", description: "आपने खोए हुए पेज पर एक अस्थिर ऑब्जेक्ट ढूँढ लिया।" } }, lab: { title: "MEDIATRIX प्रयोगशाला", accessGranted: "> पहुँच स्वीकृत", lead: "प्रयोगात्मक डिजिटल समाधान।", congratulations: "बधाई! आपकी जिज्ञासा ने इस गुप्त क्षेत्र को अनलॉक कर दिया।", storyPrompt: "कुंजी फ़ुटर में है! इस खोज को सहेजें और अपनी Story में साझा करें।", close: "बंद करें" }, modal: { eyebrow: "उपलब्धि अनलॉक हुई", close: "{achievement} उपलब्धि बंद करें" },
    share: { regionLabel: "{achievement} उपलब्धि साझा करें", shareAria: "{achievement} उपलब्धि Instagram Story पर साझा करें", creating: "Story बनाई जा रही है…", shareButton: "Instagram Story पर साझा करें", copyAria: "सुझाया गया Instagram Story टेक्स्ट कॉपी करें", copied: "कॉपी हो गया!", copyButton: "Story टेक्स्ट कॉपी करें", note: "अपने डिवाइस के शेयर मेन्यू से Instagram चुनें और Story को स्वयं पूरा करें।", assetUnavailable: "Story की इमेज अभी उपलब्ध नहीं है। फिर से कोशिश करें।", copySuccess: "Story टेक्स्ट कॉपी हो गया।", copyFailure: "Story टेक्स्ट अपने आप कॉपी नहीं हो सका। फिर से कोशिश करें।", shareCompleted: "आपके डिवाइस ने शेयर कार्रवाई पूरी कर दी। Story प्रकाशित करना आपके नियंत्रण में है।", shareCanceled: "शेयर करना रद्द हुआ। अपने आप कुछ प्रकाशित नहीं हुआ।", createFailure: "Story इमेज नहीं बनाई जा सकी। फिर से कोशिश करें।", fallbackInstructions: "Story इमेज सेव हो गई। Instagram खोलें, नई Story बनाएँ, इमेज चुनें और @mediatrixtech को मेंशन करें।", fallbackCopyFailure: "Story टेक्स्ट अपने आप कॉपी नहीं हो सका। ऊपर “Story टेक्स्ट कॉपी करें” इस्तेमाल करें।", instagramAria: "Instagram पर @mediatrixtech को नए टैब में खोलें", openInstagram: "@mediatrixtech खोलें", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "मैंने Mediatrix Tech की वेबसाइट पर एक रहस्य खोजा!", question: "क्या आप भी इसे खोज सकते हैं?", achievementUnlocked: "उपलब्धि अनलॉक हुई", secretFound: "> रहस्य मिला_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "Mediatrix Tech होमपेज", code: "HTTP / सिग्नल_खोया", message: "यह पेज दूसरी दुनिया में भाग गया।", returnHome: "होमपेज पर लौटें", objectAria: "इंटरैक्टिव कोड ऑब्जेक्ट। जाँचने के लिए पाँच बार सक्रिय करें।", objectHint: "अस्थिर ऑब्जेक्ट" }, console: "आपने कंसोल खोला। बढ़िया।\nजिज्ञासु लोग बेहतर चीज़ें बनाते हैं।\nबनाएँ। जोड़ें। रूपांतरित करें।",
  },
  ar: {
    common: { achievementUnlocked: "تم فتح الإنجاز: {achievement}" }, achievements: { digitalExplorer: { name: "المستكشف الرقمي", description: "لقد اكتشفت شيئًا لم يكن موجودًا في القائمة." }, bugHunter: { name: "صياد الأخطاء", description: "لقد تعقبت عنصرًا غير مستقر في الصفحة المفقودة." } }, lab: { title: "مختبر MEDIATRIX", accessGranted: "> تم منح الوصول", lead: "حلول رقمية تجريبية.", congratulations: "تهانينا! لقد فتح فضولك هذه المنطقة السرية.", storyPrompt: "المفتاح في تذييل الصفحة! وثّق اكتشافك وشاركه في قصتك.", close: "إغلاق" }, modal: { eyebrow: "تم فتح الإنجاز", close: "إغلاق إنجاز {achievement}" },
    share: { regionLabel: "مشاركة إنجاز {achievement}", shareAria: "مشاركة إنجاز {achievement} في قصة Instagram", creating: "جارٍ إنشاء القصة…", shareButton: "المشاركة في قصة Instagram", copyAria: "نسخ النص المقترح لقصة Instagram", copied: "تم النسخ!", copyButton: "نسخ نص القصة", note: "اختر Instagram من قائمة المشاركة في جهازك وأكمل القصة يدويًا.", assetUnavailable: "صورة القصة غير متاحة مؤقتًا. حاول مرة أخرى.", copySuccess: "تم نسخ نص القصة.", copyFailure: "تعذر نسخ نص القصة تلقائيًا. حاول مرة أخرى.", shareCompleted: "أكمل جهازك عملية المشاركة. يظل قرار نشر القصة بيدك.", shareCanceled: "أُلغيت المشاركة، ولم يُنشر أي شيء تلقائيًا.", createFailure: "تعذر إنشاء صورة القصة. حاول مرة أخرى.", fallbackInstructions: "حُفظت صورة القصة. افتح Instagram، وأنشئ قصة جديدة، واختر الصورة، وأضف @mediatrixtech كإشارة.", fallbackCopyFailure: "تعذر نسخ نص القصة تلقائيًا. استخدم «نسخ نص القصة» أعلاه.", instagramAria: "فتح @mediatrixtech على Instagram في علامة تبويب جديدة", openInstagram: "فتح @mediatrixtech", dialogTitle: "Mediatrix Tech — {achievement}" },
    story: { discovery: "لقد اكتشفت سراً في موقع Mediatrix Tech!", question: "هل يمكنك العثور عليه أيضًا؟", achievementUnlocked: "تم فتح الإنجاز", secretFound: "> تم العثور على السر_" }, notFound: { pageTitle: "404 | Mediatrix Tech", homeAria: "الصفحة الرئيسية لـ Mediatrix Tech", code: "HTTP / إشارة_مفقودة", message: "هربت هذه الصفحة إلى بُعد آخر.", returnHome: "العودة إلى الصفحة الرئيسية", objectAria: "عنصر برمجي تفاعلي. فعّله خمس مرات للتحقيق.", objectHint: "عنصر غير مستقر" }, console: "لقد فتحت وحدة التحكم. جيد.\nالأشخاص الفضوليون يصنعون أشياء أفضل.\nابتكر. تواصل. حوّل.",
  },
};

easterEggTranslations.es.story.tagline = "Crea. Conecta. Convierte.";
easterEggTranslations.fr.story.tagline = "Créez. Connectez. Convertissez.";
easterEggTranslations.de.story.tagline = "Gestalten. Verbinden. Konvertieren.";
easterEggTranslations["zh-CN"].story.tagline = "创造。连接。转化。";
easterEggTranslations.hi.story.tagline = "बनाएँ। जोड़ें। रूपांतरित करें।";
easterEggTranslations.ar.story.tagline = "ابتكر. تواصل. حوّل.";

Object.entries(digitalJunkDrawerTranslations).forEach(([locale, copy]) => {
  if (easterEggTranslations[locale]) {
    easterEggTranslations[locale].digitalJunkDrawer = copy;
  }
});

export const translations = {
  "pt-BR": {
    easterEggs: easterEggTranslations["pt-BR"],
    metaTitle: "Criação de sites profissionais | Mediatrix Tech",
    metaDescription: "Sites rápidos, responsivos e personalizados para pequenas empresas, profissionais, eventos e agronegócio em Santa Maria, no Brasil e no exterior.",
    skip: "Pular para o conteúdo",
    nav: ["Início", "Serviços", "Portfólio", "Empresa", "Contato"],
    primaryNavigation: "Navegação principal",
    mobileNavigation: "Navegação móvel",
    language: "Idioma",
    openMenu: "Abrir menu",
    closeMenu: "Fechar menu",
    quote: "Solicitar uma avaliação gratuita do site",
    hero: {
      logoAlt: "Logo da Mediatrix Tech",
      title: "Mais clientes. Mais receita. Crescimento da receita até 27% mais rápido.*",
      footnote: "*Com base em uma pesquisa da Deloitte Access Economics que compara PMEs com presença digital avançada a empresas sem presença online.",
      primaryCta: "Solicitar uma avaliação gratuita do site",
      secondaryCta: "Ver nosso trabalho",
    },
    servicesSection: {
      eyebrow: "Serviços",
      title: "O que podemos criar para você",
      description: "Do primeiro site a uma ferramenta personalizada, cada projeto começa com um objetivo claro e um escopo definido.",
    },
    services: [
      { id: "site", title: "Sites profissionais e institucionais", shortTitle: "Sites profissionais", subtitle: "Gere confiança. Atraia mais clientes.", description: "Sites rápidos e responsivos para explicar seus serviços, fortalecer a confiança e facilitar o contato.", benefit: "Uma presença digital própria, clara e preparada para crescer." },
      { id: "landing", title: "Landing pages", shortTitle: "Landing pages", subtitle: "Transforme visitantes em leads e vendas.", description: "Páginas focadas em campanhas, lançamentos, serviços ou captação de novos contatos.", benefit: "Uma mensagem objetiva com um próximo passo fácil de entender." },
      { id: "custom", title: "Sistemas e soluções personalizadas", shortTitle: "Soluções web personalizadas", subtitle: "Ferramentas criadas para o seu negócio.", description: "Ferramentas simples, formulários, painéis e fluxos digitais desenvolvidos conforme a rotina da empresa.", benefit: "Menos trabalho manual e uma operação mais organizada." },
      { id: "media", title: "Edição de imagens, vídeos e áudio", shortTitle: "Edição de mídia", description: "Tratamento de conteúdo para produtos, eventos, redes sociais, apresentações e materiais institucionais.", benefit: "Comunicação visual e sonora mais profissional e consistente." },
      { id: "event", title: "Páginas para eventos com QR Code", shortTitle: "Sites para eventos e QR Code", subtitle: "Experiências simples que as pessoas adoram usar.", description: "Experiências personalizadas para convidados enviarem, aprovarem e compartilharem fotos e vídeos.", benefit: "Participação simples pelo celular, sem exigir aplicativo." },
      { id: "agri", title: "Soluções digitais para o agronegócio", shortTitle: "Soluções para o agronegócio", subtitle: "Ferramentas digitais criadas para a agricultura.", description: "Sites, painéis e experiências digitais para apresentar operações, dados e serviços do setor agrícola.", benefit: "Tecnologia aplicada a informações úteis para o campo e para o negócio." },
      { id: "care", title: "Manutenção e atualização de sites", shortTitle: "Cuidado e suporte para sites", subtitle: "Atualizações, melhorias e suporte contínuo.", description: "Ajustes de conteúdo, melhorias técnicas e acompanhamento para manter o site seguro e atual.", benefit: "Seu site continua funcionando bem depois da entrega." },
    ],
    portfolioSection: { eyebrow: "Portfólio", title: "Projetos selecionados.", description: "Alguns trabalhos que unem clareza, experiência e resultado.", view: "Ver projeto", videoDemo: "Demonstração do projeto", screenshot: "Captura de tela do projeto" },
    projects: [
      { name: "AgriClimate Pro", category: "Desenvolvimento Web · AgTech", description: "Experiência digital para apoiar decisões agrícolas com dados climáticos." },
      { name: "Frasson LLC", category: "Desenvolvimento Web", description: "Site empresarial objetivo, criado para apresentar serviços e facilitar o contato." },
      { name: "Event QR Code", category: "Experiência digital para eventos", description: "Fluxo simples por QR Code para convidados enviarem fotos e vídeos." },
      { name: "Cafeteria", category: "Desenvolvimento Web · Alimentação", description: "Site acolhedor e responsivo para apresentar a experiência da cafeteria e facilitar o acesso ao cardápio." },
      { name: "Oficina Mecânica", category: "Desenvolvimento Web · Serviços Automotivos", description: "Site responsivo para apresentar os serviços da oficina e facilitar o contato com clientes da região." },
      { type: "collaboration", collection: "Colaboração selecionada · IA e dados", name: "Projeto Internacional de Dados para IA", category: "Treinamento de IA e coleta de dados", description: "Contribuímos para uma iniciativa de treinamento de IA em grande escala por meio de coleta estruturada de dados, validação e entrega com controle de qualidade.", tagsLabel: "Competências da colaboração", tags: ["Dados para treinamento de IA", "Coleta de dados", "Garantia de qualidade"], metrics: [{ value: "30+ horas", label: "Dados estruturados entregues" }] },
    ],
    company: {
      eyebrow: "Empresa", title: "Feito por pessoas", description: "Pessoas reais criando soluções digitais claras e úteis para necessidades reais de negócios.",
      localSeo: { text: "A Mediatrix Tech desenvolve sites e soluções digitais para empresas de Santa Maria, do Rio Grande do Sul e de outras regiões do Brasil e do mundo.", link: "Criação de sites em Santa Maria, RS" },
      facts: [
        ["Conduzido por pessoas", "Pessoas reais. Comunicação direta."],
        ["Feito para você", "Soluções moldadas ao seu negócio."],
        ["Processo claro", "Comunicação simples. Sem complexidade desnecessária."],
        ["No mundo todo", "Trabalhando com empresas onde quer que estejam."],
      ],
    },
    contact: {
      eyebrow: "Contato", title: "Conte o que sua empresa precisa melhorar no digital.", description: "Envie uma mensagem para solicitar uma avaliação inicial, esclarecer dúvidas ou conversar sobre um novo projeto.", channelsLabel: "Canais de contato",
      channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["E-mail", "mediatrixtech@proton.me"], ["Perfil na Upwork", "Projetos internacionais"]],
      form: { title: "Envie uma mensagem", description: "Conte brevemente o que você precisa.", name: "Nome", email: "E-mail", service: "Serviço de interesse", chooseService: "Selecione um serviço", message: "Mensagem", send: "Enviar mensagem", sending: "Enviando...", success: "Mensagem enviada com sucesso. Em breve entraremos em contato.", error: "Não foi possível enviar. Tente novamente ou fale conosco pelo WhatsApp.", subject: "Nova mensagem pelo site Mediatrix Tech" },
    },
    rights: "Todos os direitos reservados.",
  },

  en: {
    easterEggs: easterEggTranslations.en,
    metaTitle: "Professional websites for small businesses | Mediatrix Tech",
    metaDescription: "Fast, responsive and personalized websites for small businesses, service providers, events and agricultural companies worldwide.",
    skip: "Skip to content",
    nav: ["Home", "Services", "Portfolio", "Company", "Contact"],
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    language: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    quote: "Request a free website review",
    hero: { logoAlt: "Mediatrix Tech logo", title: "More clients. More income. Up to 27% faster revenue growth.*", footnote: "*Based on Deloitte Access Economics research comparing advanced digitally engaged SMBs with offline businesses.", primaryCta: "Request a free website review", secondaryCta: "View our work" },
    servicesSection: { eyebrow: "Services", title: "What we can build for you", description: "From a first website to a custom tool, every project starts with a clear goal and a defined scope." },
    services: [
      { id: "site", title: "Professional and company websites", shortTitle: "Professional Websites", subtitle: "Build trust. Attract more clients.", description: "Fast, responsive websites that explain your services, build trust and make it easy to get in touch.", benefit: "A clear online presence your business can keep building on." },
      { id: "landing", title: "Landing pages", shortTitle: "Landing Pages", subtitle: "Turn visitors into leads and sales.", description: "Focused pages for campaigns, launches, individual services and lead generation.", benefit: "A direct message with an easy next step for visitors." },
      { id: "custom", title: "Custom systems and digital solutions", shortTitle: "Custom Web Solutions", subtitle: "Tools built around your business.", description: "Simple tools, forms, dashboards and workflows developed around the way your business operates.", benefit: "Less manual work and a more organized process." },
      { id: "media", title: "Image, video and audio editing", shortTitle: "Media editing", description: "Professional content editing for products, events, social media, presentations and company materials.", benefit: "More consistent visual and audio communication." },
      { id: "event", title: "QR Code event websites", shortTitle: "Event & QR Websites", subtitle: "Simple experiences people love to use.", description: "Custom experiences for guests to upload, approve and share photos and videos from their phones.", benefit: "Simple participation without requiring an app." },
      { id: "agri", title: "Digital solutions for agriculture", shortTitle: "Agribusiness Solutions", subtitle: "Digital tools built for agriculture.", description: "Websites, dashboards and digital experiences that present agricultural operations, services and data.", benefit: "Technology applied to useful information for the field and the business." },
      { id: "care", title: "Website maintenance and updates", shortTitle: "Website Care & Support", subtitle: "Updates, improvements, and ongoing support.", description: "Content changes, technical improvements and ongoing care to keep your website current and reliable.", benefit: "Your website keeps working well after launch." },
    ],
    portfolioSection: { eyebrow: "Portfolio", title: "Selected projects.", description: "Work that combines clarity, experience, and results.", view: "View project", videoDemo: "Project demo", screenshot: "Project screenshot" },
    projects: [
      { name: "AgriClimate Pro", category: "Web Development · AgTech", description: "A digital experience supporting agricultural decisions with climate data." },
      { name: "Frasson LLC", category: "Web Development", description: "A focused business website designed to present services and simplify contact." },
      { name: "Event QR Code", category: "Digital event experience", description: "A simple QR Code flow for guests to upload photos and videos." },
      { name: "Cafeteria", category: "Web Development · Food & Beverage", description: "A warm, responsive website presenting the café experience and providing easy access to the menu." },
      { name: "Auto Repair Shop", category: "Web Development · Automotive Services", description: "A responsive website presenting the repair shop’s services and making it easy for local customers to get in touch." },
      { type: "collaboration", collection: "Selected Collaboration · AI & Data", name: "International AI Data Project", category: "AI Training & Data Collection", description: "Contributed to a large-scale AI training initiative through structured data collection, validation, and quality-controlled delivery.", tagsLabel: "Collaboration capabilities", tags: ["AI Training Data", "Data Collection", "Quality Assurance"], metrics: [{ value: "30+ hours", label: "Structured data delivered" }] },
    ],
    company: { eyebrow: "Company", title: "Made by Humans", description: "Real people building clear, useful digital solutions around real business needs.", localSeo: { text: "Mediatrix Tech develops websites and digital solutions for businesses in Santa Maria, Rio Grande do Sul, other regions of Brazil and worldwide.", link: "Website development in Santa Maria, RS" }, facts: [["Human-led", "Real people. Direct communication."], ["Built around you", "Solutions shaped around your business."], ["Clear process", "Simple communication. No unnecessary complexity."], ["Worldwide", "Working with businesses wherever they are."]] },
    contact: {
      eyebrow: "Contact", title: "Tell us what your business needs to improve online.", description: "Send a message to request an initial review, ask a question or discuss a new project.", channelsLabel: "Contact channels",
      channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["Email", "mediatrixtech@proton.me"], ["Upwork profile", "International projects"]],
      form: { title: "Send a message", description: "Briefly tell us what you need.", name: "Name", email: "Email", service: "Service of interest", chooseService: "Select a service", message: "Message", send: "Send message", sending: "Sending...", success: "Message sent successfully. We will be in touch soon.", error: "We could not send your message. Please try again or contact us on WhatsApp.", subject: "New message from the Mediatrix Tech website" },
    },
    rights: "All rights reserved.",
  },

  es: {
    easterEggs: easterEggTranslations.es,
    metaTitle: "Sitios web profesionales y soluciones digitales | Mediatrix Tech",
    metaDescription: "Mediatrix Tech crea sitios web y contenido visual profesional para empresas de todo el mundo.",
    skip: "Saltar al contenido",
    nav: ["Inicio", "Servicios", "Portafolio", "Empresa", "Contacto"],
    primaryNavigation: "Navegación principal", mobileNavigation: "Navegación móvil", language: "Idioma", openMenu: "Abrir menú", closeMenu: "Cerrar menú", quote: "Solicitar una revisión gratuita del sitio web",
    hero: { logoAlt: "Logotipo de Mediatrix Tech", title: "Más clientes. Más ingresos. Un crecimiento de los ingresos hasta un 27 % más rápido.*", footnote: "*Basado en una investigación de Deloitte Access Economics que compara pymes con una presencia digital avanzada con empresas sin presencia en línea.", primaryCta: "Solicitar una revisión gratuita del sitio web", secondaryCta: "Ver nuestro trabajo" },
    servicesSection: { eyebrow: "Servicios", title: "Lo que podemos crear para ti", description: "Desde un primer sitio web hasta una herramienta personalizada, cada proyecto comienza con un objetivo claro y un alcance definido." },
    services: [
      { id: "site", title: "Sitios web profesionales", shortTitle: "Sitios web profesionales", subtitle: "Genera confianza. Atrae a más clientes.", description: "Sitios claros y responsivos para presentar tu negocio.", benefit: "Una presencia digital profesional." },
      { id: "landing", title: "Landing pages", shortTitle: "Landing pages", subtitle: "Convierte visitantes en leads y ventas.", description: "Páginas enfocadas en campañas y conversiones.", benefit: "Un próximo paso claro para cada visitante." },
      { id: "custom", title: "Soluciones web personalizadas", shortTitle: "Soluciones web personalizadas", subtitle: "Herramientas creadas para tu negocio.", description: "Herramientas digitales adaptadas a tu operación.", benefit: "Procesos más simples y organizados." },
      { id: "media", title: "Edición de imágenes, video y audio", shortTitle: "Edición multimedia", description: "Edición profesional para productos, eventos y contenido digital.", benefit: "Comunicación visual y sonora consistente." },
      { id: "event", title: "Sitios para eventos y códigos QR", shortTitle: "Sitios para eventos y códigos QR", subtitle: "Experiencias simples que a la gente le encanta usar.", description: "Experiencias móviles para invitados y eventos.", benefit: "Participación sencilla sin instalar aplicaciones." },
      { id: "agri", title: "Soluciones para el agronegocio", shortTitle: "Soluciones para el agronegocio", subtitle: "Herramientas digitales creadas para la agricultura.", description: "Sitios y herramientas digitales para el sector agrícola.", benefit: "Tecnología útil para el campo y el negocio." },
      { id: "care", title: "Cuidado y soporte de sitios web", shortTitle: "Cuidado y soporte de sitios web", subtitle: "Actualizaciones, mejoras y soporte continuo.", description: "Mantenimiento para conservar tu sitio actualizado y confiable.", benefit: "Acompañamiento después del lanzamiento." },
    ],
    portfolioSection: { eyebrow: "Portafolio", title: "Proyectos seleccionados.", description: "Trabajos que combinan claridad, experiencia y resultados.", view: "Ver proyecto", videoDemo: "Demostración del proyecto", screenshot: "Captura de pantalla del proyecto" },
    projects: [{ name: "AgriClimate Pro", category: "Desarrollo Web · AgTech", description: "Una experiencia digital que apoya decisiones agrícolas con datos climáticos." }, { name: "Frasson LLC", category: "Desarrollo Web", description: "Un sitio empresarial claro, creado para presentar servicios y facilitar el contacto." }, { name: "Event QR Code", category: "Experiencia digital para eventos", description: "Un flujo sencillo con código QR para que los invitados envíen fotos y videos." }, { name: "Cafeteria", category: "Desarrollo Web · Gastronomía", description: "Un sitio cálido y responsivo para presentar la experiencia de la cafetería y facilitar el acceso al menú." }, { name: "Taller Mecánico", category: "Desarrollo Web · Servicios Automotrices", description: "Un sitio responsivo que presenta los servicios del taller y facilita el contacto con clientes de la zona." }, { type: "collaboration", collection: "Colaboración seleccionada · IA y datos", name: "Proyecto Internacional de Datos para IA", category: "Entrenamiento de IA y recopilación de datos", description: "Contribuimos a una iniciativa de entrenamiento de IA a gran escala mediante la recopilación estructurada de datos, la validación y una entrega con control de calidad.", tagsLabel: "Capacidades de la colaboración", tags: ["Datos para entrenamiento de IA", "Recopilación de datos", "Garantía de calidad"], metrics: [{ value: "30+ horas", label: "Datos estructurados entregados" }] }],
    company: { eyebrow: "Empresa", title: "Hecho por personas", description: "Personas reales creando soluciones digitales claras y útiles para necesidades reales de negocio.", localSeo: { text: "Mediatrix Tech desarrolla sitios web y soluciones digitales para empresas de Santa Maria, Rio Grande do Sul, otras regiones de Brasil y del mundo.", link: "Creación de sitios web en Santa Maria, RS" }, facts: [["Liderado por personas", "Personas reales. Comunicación directa."], ["Creado para ti", "Soluciones adaptadas a tu negocio."], ["Proceso claro", "Comunicación sencilla. Sin complejidad innecesaria."], ["En todo el mundo", "Trabajamos con empresas dondequiera que estén."]] },
    contact: { eyebrow: "Contacto", title: "¿Hablamos de tu proyecto?", description: "Elige el canal más cómodo o envíanos un mensaje mediante el formulario.", channelsLabel: "Canales de contacto", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["Correo electrónico", "mediatrixtech@proton.me"], ["Perfil en Upwork", "Proyectos internacionales"]], form: { title: "Envía un mensaje", description: "Cuéntanos brevemente qué necesitas.", name: "Nombre", email: "Correo electrónico", service: "Servicio de interés", chooseService: "Selecciona un servicio", message: "Mensaje", send: "Enviar mensaje", sending: "Enviando...", success: "Mensaje enviado correctamente. Nos pondremos en contacto pronto.", error: "No pudimos enviar tu mensaje. Inténtalo de nuevo o escríbenos por WhatsApp.", subject: "Nuevo mensaje desde el sitio de Mediatrix Tech" } },
    rights: "Todos los derechos reservados.",
  },

  fr: {
    easterEggs: easterEggTranslations.fr,
    metaTitle: "Sites web professionnels et solutions numériques | Mediatrix Tech",
    metaDescription: "Mediatrix Tech crée des sites web et des contenus visuels professionnels pour les entreprises du monde entier.",
    skip: "Aller au contenu", nav: ["Accueil", "Services", "Portfolio", "Entreprise", "Contact"], primaryNavigation: "Navigation principale", mobileNavigation: "Navigation mobile", language: "Langue", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", quote: "Demander un audit gratuit du site web",
    hero: { logoAlt: "Logo de Mediatrix Tech", title: "Plus de clients. Plus de revenus. Une croissance du chiffre d’affaires jusqu’à 27 % plus rapide.*", footnote: "*D’après une étude de Deloitte Access Economics comparant les PME très avancées sur le plan numérique aux entreprises hors ligne.", primaryCta: "Demander un audit gratuit du site web", secondaryCta: "Voir nos réalisations" },
    servicesSection: { eyebrow: "Services", title: "Ce que nous pouvons créer pour vous", description: "Du premier site web à un outil sur mesure, chaque projet commence par un objectif clair et un périmètre défini." },
    services: [{ id: "site", title: "Sites web professionnels", shortTitle: "Sites web professionnels", subtitle: "Inspirez confiance. Attirez plus de clients.", description: "Des sites clairs et adaptatifs pour présenter votre entreprise.", benefit: "Une présence numérique professionnelle." }, { id: "landing", title: "Pages d’atterrissage", shortTitle: "Pages d’atterrissage", subtitle: "Transformez les visiteurs en prospects et en ventes.", description: "Des pages ciblées pour les campagnes et la conversion.", benefit: "Une prochaine étape claire pour chaque visiteur." }, { id: "custom", title: "Solutions web sur mesure", shortTitle: "Solutions web sur mesure", subtitle: "Des outils conçus autour de votre entreprise.", description: "Des outils numériques adaptés à votre fonctionnement.", benefit: "Des processus plus simples et mieux organisés." }, { id: "media", title: "Retouche photo, vidéo et audio", shortTitle: "Édition multimédia", description: "Des retouches professionnelles pour produits, événements et contenus numériques.", benefit: "Une communication visuelle et sonore cohérente." }, { id: "event", title: "Sites événementiels et QR codes", shortTitle: "Sites événementiels et QR codes", subtitle: "Des expériences simples que les gens aiment utiliser.", description: "Des expériences mobiles conçues pour les invités et les événements.", benefit: "Une participation simple, sans application." }, { id: "agri", title: "Solutions pour l’agriculture", shortTitle: "Solutions pour l’agriculture", subtitle: "Des outils numériques conçus pour l’agriculture.", description: "Des sites et outils numériques pour le secteur agricole.", benefit: "Une technologie utile pour le terrain et l’entreprise." }, { id: "care", title: "Maintenance et assistance web", shortTitle: "Maintenance et assistance web", subtitle: "Mises à jour, améliorations et assistance continue.", description: "Un suivi pour garder votre site fiable et à jour.", benefit: "Un accompagnement après le lancement." }],
    portfolioSection: { eyebrow: "Portfolio", title: "Projets sélectionnés.", description: "Des réalisations qui allient clarté, expérience et résultats.", view: "Voir le projet", videoDemo: "Démonstration du projet", screenshot: "Capture d’écran du projet" },
    projects: [{ name: "AgriClimate Pro", category: "Développement Web · AgTech", description: "Une expérience numérique qui facilite les décisions agricoles grâce aux données climatiques." }, { name: "Frasson LLC", category: "Développement Web", description: "Un site d’entreprise clair, conçu pour présenter les services et faciliter le contact." }, { name: "Event QR Code", category: "Expérience numérique événementielle", description: "Un parcours simple par QR Code permettant aux invités d’envoyer photos et vidéos." }, { name: "Cafeteria", category: "Développement Web · Restauration", description: "Un site chaleureux et adaptatif qui présente l’expérience du café et facilite l’accès au menu." }, { name: "Garage Automobile", category: "Développement Web · Services Automobiles", description: "Un site adaptatif qui présente les services du garage et facilite le contact avec les clients locaux." }, { type: "collaboration", collection: "Collaboration sélectionnée · IA et données", name: "Projet international de données pour l’IA", category: "Entraînement de l’IA et collecte de données", description: "Contribution à une initiative d’entraînement de l’IA à grande échelle grâce à la collecte structurée de données, à leur validation et à une livraison contrôlée en matière de qualité.", tagsLabel: "Compétences de la collaboration", tags: ["Données d’entraînement IA", "Collecte de données", "Assurance qualité"], metrics: [{ value: "30+ heures", label: "Données structurées livrées" }] }],
    company: { eyebrow: "Entreprise", title: "Créé par des humains", description: "De vraies personnes créent des solutions numériques claires et utiles, adaptées aux besoins réels des entreprises.", localSeo: { text: "Mediatrix Tech conçoit des sites web et des solutions numériques pour les entreprises de Santa Maria, du Rio Grande do Sul, d’autres régions du Brésil et du monde entier.", link: "Création de sites web à Santa Maria, RS" }, facts: [["Guidé par l’humain", "De vraies personnes. Une communication directe."], ["Conçu autour de vous", "Des solutions adaptées à votre entreprise."], ["Processus clair", "Une communication simple. Aucune complexité inutile."], ["Dans le monde entier", "Nous travaillons avec les entreprises où qu’elles soient."]] },
    contact: { eyebrow: "Contact", title: "Parlons de votre projet.", description: "Choisissez le canal le plus pratique ou envoyez-nous un message via le formulaire.", channelsLabel: "Canaux de contact", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["E-mail", "mediatrixtech@proton.me"], ["Profil Upwork", "Projets internationaux"]], form: { title: "Envoyer un message", description: "Expliquez-nous brièvement ce dont vous avez besoin.", name: "Nom", email: "E-mail", service: "Service recherché", chooseService: "Sélectionnez un service", message: "Message", send: "Envoyer le message", sending: "Envoi en cours...", success: "Message envoyé. Nous vous répondrons bientôt.", error: "Votre message n’a pas pu être envoyé. Réessayez ou contactez-nous sur WhatsApp.", subject: "Nouveau message depuis le site Mediatrix Tech" } },
    rights: "Tous droits réservés.",
  },

  de: {
    easterEggs: easterEggTranslations.de,
    metaTitle: "Professionelle Websites und digitale Lösungen | Mediatrix Tech",
    metaDescription: "Mediatrix Tech erstellt professionelle Websites und visuelle Inhalte für Unternehmen weltweit.",
    skip: "Zum Inhalt springen", nav: ["Start", "Leistungen", "Portfolio", "Unternehmen", "Kontakt"], primaryNavigation: "Hauptnavigation", mobileNavigation: "Mobile Navigation", language: "Sprache", openMenu: "Menü öffnen", closeMenu: "Menü schließen", quote: "Kostenlosen Website-Check anfordern",
    hero: { logoAlt: "Logo von Mediatrix Tech", title: "Mehr Kunden. Mehr Umsatz. Bis zu 27 % schnelleres Umsatzwachstum.*", footnote: "*Basierend auf einer Studie von Deloitte Access Economics, die digital fortschrittliche KMU mit Offline-Unternehmen vergleicht.", primaryCta: "Kostenlosen Website-Check anfordern", secondaryCta: "Unsere Arbeiten ansehen" },
    servicesSection: { eyebrow: "Leistungen", title: "Was wir für Sie entwickeln können", description: "Von der ersten Website bis zu einem individuellen Tool beginnt jedes Projekt mit einem klaren Ziel und einem definierten Umfang." },
    services: [{ id: "site", title: "Professionelle Websites", shortTitle: "Professionelle Websites", subtitle: "Vertrauen schaffen. Mehr Kunden gewinnen.", description: "Klare, responsive Websites für Ihr Unternehmen.", benefit: "Ein professioneller digitaler Auftritt." }, { id: "landing", title: "Landingpages", shortTitle: "Landingpages", subtitle: "Besucher in Leads und Verkäufe verwandeln.", description: "Fokussierte Seiten für Kampagnen und Conversions.", benefit: "Ein klarer nächster Schritt für jeden Besucher." }, { id: "custom", title: "Individuelle Weblösungen", shortTitle: "Individuelle Weblösungen", subtitle: "Werkzeuge, die auf Ihr Unternehmen zugeschnitten sind.", description: "Digitale Werkzeuge passend zu Ihren Abläufen.", benefit: "Einfachere und besser organisierte Prozesse." }, { id: "media", title: "Bild-, Video- und Audiobearbeitung", shortTitle: "Medienbearbeitung", description: "Professionelle Bearbeitung für Produkte, Veranstaltungen und digitale Inhalte.", benefit: "Einheitliche visuelle und akustische Kommunikation." }, { id: "event", title: "Event- und QR-Websites", shortTitle: "Event- und QR-Websites", subtitle: "Einfache Erlebnisse, die Menschen gerne nutzen.", description: "Mobile Erlebnisse für Gäste und Veranstaltungen.", benefit: "Einfache Teilnahme ohne zusätzliche App." }, { id: "agri", title: "Lösungen für die Landwirtschaft", shortTitle: "Lösungen für die Landwirtschaft", subtitle: "Digitale Werkzeuge für die Landwirtschaft.", description: "Websites und digitale Werkzeuge für den Agrarsektor.", benefit: "Nützliche Technologie für Feld und Betrieb." }, { id: "care", title: "Website-Pflege und Support", shortTitle: "Website-Pflege und Support", subtitle: "Aktualisierungen, Verbesserungen und laufender Support.", description: "Laufende Pflege für eine aktuelle und zuverlässige Website.", benefit: "Begleitung auch nach dem Start." }],
    portfolioSection: { eyebrow: "Portfolio", title: "Ausgewählte Projekte.", description: "Arbeiten, die Klarheit, Erfahrung und Ergebnisse verbinden.", view: "Projekt ansehen", videoDemo: "Projekt-Demo", screenshot: "Projekt-Screenshot" },
    projects: [{ name: "AgriClimate Pro", category: "Webentwicklung · AgTech", description: "Eine digitale Lösung, die landwirtschaftliche Entscheidungen mit Klimadaten unterstützt." }, { name: "Frasson LLC", category: "Webentwicklung", description: "Eine klare Unternehmenswebsite zur Präsentation von Leistungen und für eine einfache Kontaktaufnahme." }, { name: "Event QR Code", category: "Digitale Event-Lösung", description: "Ein einfacher QR-Code-Ablauf, über den Gäste Fotos und Videos hochladen können." }, { name: "Cafeteria", category: "Webentwicklung · Gastronomie", description: "Eine einladende, responsive Website, die das Café-Erlebnis präsentiert und den Zugang zur Speisekarte erleichtert." }, { name: "Autowerkstatt", category: "Webentwicklung · Kfz-Service", description: "Eine responsive Website, die die Werkstattleistungen präsentiert und lokalen Kunden die Kontaktaufnahme erleichtert." }, { type: "collaboration", collection: "Ausgewählte Zusammenarbeit · KI & Daten", name: "Internationales KI-Datenprojekt", category: "KI-Training und Datenerhebung", description: "Beitrag zu einer groß angelegten KI-Trainingsinitiative durch strukturierte Datenerhebung, Validierung und qualitätskontrollierte Lieferung.", tagsLabel: "Kompetenzen der Zusammenarbeit", tags: ["KI-Trainingsdaten", "Datenerhebung", "Qualitätssicherung"], metrics: [{ value: "30+ Stunden", label: "Strukturierte Daten geliefert" }] }],
    company: { eyebrow: "Unternehmen", title: "Von Menschen gemacht", description: "Echte Menschen entwickeln klare, nützliche digitale Lösungen für reale Geschäftsanforderungen.", localSeo: { text: "Mediatrix Tech entwickelt Websites und digitale Lösungen für Unternehmen in Santa Maria, Rio Grande do Sul, anderen Regionen Brasiliens und weltweit.", link: "Website-Erstellung in Santa Maria, RS" }, facts: [["Von Menschen geführt", "Echte Menschen. Direkte Kommunikation."], ["Auf Sie zugeschnitten", "Lösungen rund um Ihr Unternehmen."], ["Klarer Prozess", "Einfache Kommunikation. Keine unnötige Komplexität."], ["Weltweit", "Wir arbeiten mit Unternehmen, wo immer sie sind."]] },
    contact: { eyebrow: "Kontakt", title: "Lassen Sie uns über Ihr Projekt sprechen.", description: "Wählen Sie den bequemsten Kanal oder senden Sie uns eine Nachricht über das Formular.", channelsLabel: "Kontaktmöglichkeiten", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["E-Mail", "mediatrixtech@proton.me"], ["Upwork-Profil", "Internationale Projekte"]], form: { title: "Nachricht senden", description: "Beschreiben Sie kurz, was Sie benötigen.", name: "Name", email: "E-Mail", service: "Gewünschte Leistung", chooseService: "Leistung auswählen", message: "Nachricht", send: "Nachricht senden", sending: "Wird gesendet...", success: "Nachricht erfolgreich gesendet. Wir melden uns in Kürze.", error: "Ihre Nachricht konnte nicht gesendet werden. Versuchen Sie es erneut oder kontaktieren Sie uns über WhatsApp.", subject: "Neue Nachricht von der Mediatrix-Tech-Website" } },
    rights: "Alle Rechte vorbehalten.",
  },

  "zh-CN": {
    easterEggs: easterEggTranslations["zh-CN"],
    metaTitle: "专业网站与数字解决方案 | Mediatrix Tech",
    metaDescription: "Mediatrix Tech 为全球企业打造专业网站和视觉内容。",
    skip: "跳到主要内容", nav: ["首页", "服务", "作品集", "公司", "联系"], primaryNavigation: "主导航", mobileNavigation: "移动端导航", language: "语言", openMenu: "打开菜单", closeMenu: "关闭菜单", quote: "申请免费网站评估",
    hero: { logoAlt: "Mediatrix Tech 标志", title: "更多客户。更多收入。营收增长速度最高可提升 27%。*", footnote: "*基于 Deloitte Access Economics 的研究，该研究将数字化参与度高的中小企业与离线经营的企业进行了比较。", primaryCta: "申请免费网站评估", secondaryCta: "查看我们的作品" },
    servicesSection: { eyebrow: "服务", title: "我们能为您打造什么", description: "从第一个网站到定制工具，每个项目都以清晰的目标和明确的范围开始。" },
    services: [{ id: "site", title: "专业网站", shortTitle: "专业网站", subtitle: "建立信任，吸引更多客户。", description: "清晰、响应式的企业网站。", benefit: "专业可靠的数字形象。" }, { id: "landing", title: "着陆页", shortTitle: "着陆页", subtitle: "将访客转化为潜在客户和销售。", description: "专注于推广和转化的页面。", benefit: "为每位访客提供明确的下一步。" }, { id: "custom", title: "定制 Web 解决方案", shortTitle: "定制 Web 解决方案", subtitle: "围绕您的业务打造的工具。", description: "适配业务流程的数字工具。", benefit: "让流程更简单、更有条理。" }, { id: "media", title: "图片、视频和音频编辑", shortTitle: "多媒体编辑", description: "面向产品、活动和数字内容的专业编辑。", benefit: "保持视觉与声音传播的一致性。" }, { id: "event", title: "活动与二维码网站", shortTitle: "活动与二维码网站", subtitle: "简单易用、让人乐于使用的体验。", description: "面向宾客和活动的移动体验。", benefit: "无需安装应用即可轻松参与。" }, { id: "agri", title: "农业数字解决方案", shortTitle: "农业数字解决方案", subtitle: "专为农业打造的数字工具。", description: "面向农业领域的网站和数字工具。", benefit: "服务田间与经营的实用技术。" }, { id: "care", title: "网站维护与支持", shortTitle: "网站维护与支持", subtitle: "更新、改进与持续支持。", description: "让网站保持可靠和最新的持续维护。", benefit: "上线后的长期支持。" }],
    portfolioSection: { eyebrow: "作品集", title: "精选项目。", description: "兼顾清晰表达、用户体验与实际成果的代表作品。", view: "查看项目", videoDemo: "项目演示", screenshot: "项目截图" },
    projects: [{ name: "AgriClimate Pro", category: "网站开发 · 农业科技", description: "利用气候数据辅助农业决策的数字化体验。" }, { name: "Frasson LLC", category: "网站开发", description: "简洁的企业网站，用于展示服务并方便客户联系。" }, { name: "Event QR Code", category: "活动数字体验", description: "宾客可通过二维码轻松上传照片和视频。" }, { name: "Cafeteria", category: "网站开发 · 餐饮", description: "温馨的响应式网站，展示咖啡馆体验并让访客轻松查看菜单。" }, { name: "汽车维修店", category: "网站开发 · 汽车服务", description: "响应式网站，用于展示维修服务并方便本地客户联系。" }, { type: "collaboration", collection: "精选合作 · AI 与数据", name: "国际 AI 数据项目", category: "AI 训练与数据采集", description: "通过结构化数据采集、验证和质量控制交付，为一项大规模 AI 训练计划作出贡献。", tagsLabel: "合作能力", tags: ["AI 训练数据", "数据采集", "质量保证"], metrics: [{ value: "30+ 小时", label: "已交付结构化数据" }] }],
    company: { eyebrow: "公司", title: "由真人打造", description: "由真实的人，为真实的业务需求打造清晰、实用的数字解决方案。", localSeo: { text: "Mediatrix Tech 为圣玛丽亚、南里奥格兰德州、巴西其他地区及全球企业开发网站和数字解决方案。", link: "圣玛丽亚（RS）网站开发" }, facts: [["以人为本", "真人协作，直接沟通。"], ["围绕您打造", "根据您的业务塑造解决方案。"], ["流程清晰", "沟通简单，不增加不必要的复杂性。"], ["服务全球", "无论企业身在何处，我们都能与之合作。"]] },
    contact: { eyebrow: "联系", title: "聊聊您的项目吧。", description: "请选择最方便的联系方式，或通过表单给我们留言。", channelsLabel: "联系方式", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["电子邮件", "mediatrixtech@proton.me"], ["Upwork 主页", "国际项目"]], form: { title: "发送消息", description: "请简要说明您的需求。", name: "姓名", email: "电子邮件", service: "感兴趣的服务", chooseService: "请选择一项服务", message: "消息", send: "发送消息", sending: "正在发送...", success: "消息已成功发送。我们会尽快与您联系。", error: "消息发送失败。请重试或通过 WhatsApp 联系我们。", subject: "来自 Mediatrix Tech 网站的新消息" } },
    rights: "版权所有。",
  },

  hi: {
    easterEggs: easterEggTranslations.hi,
    metaTitle: "पेशेवर वेबसाइट और डिजिटल समाधान | Mediatrix Tech",
    metaDescription: "Mediatrix Tech दुनिया भर के व्यवसायों के लिए पेशेवर वेबसाइट और विज़ुअल कंटेंट बनाता है।",
    skip: "मुख्य सामग्री पर जाएँ", nav: ["होम", "सेवाएँ", "पोर्टफोलियो", "कंपनी", "संपर्क"], primaryNavigation: "मुख्य नेविगेशन", mobileNavigation: "मोबाइल नेविगेशन", language: "भाषा", openMenu: "मेन्यू खोलें", closeMenu: "मेन्यू बंद करें", quote: "मुफ़्त वेबसाइट समीक्षा का अनुरोध करें",
    hero: { logoAlt: "Mediatrix Tech का लोगो", title: "ज़्यादा ग्राहक। ज़्यादा आय। राजस्व वृद्धि 27% तक तेज़।*", footnote: "*Deloitte Access Economics के शोध पर आधारित, जिसमें डिजिटल रूप से उन्नत लघु और मध्यम व्यवसायों की तुलना ऑफ़लाइन व्यवसायों से की गई है।", primaryCta: "मुफ़्त वेबसाइट समीक्षा का अनुरोध करें", secondaryCta: "हमारा काम देखें" },
    servicesSection: { eyebrow: "सेवाएँ", title: "हम आपके लिए क्या बना सकते हैं", description: "पहली वेबसाइट से लेकर कस्टम टूल तक, हर प्रोजेक्ट एक स्पष्ट लक्ष्य और परिभाषित दायरे से शुरू होता है।" },
    services: [{ id: "site", title: "पेशेवर वेबसाइटें", shortTitle: "पेशेवर वेबसाइटें", subtitle: "भरोसा बनाएँ। अधिक ग्राहक आकर्षित करें।", description: "आपके व्यवसाय के लिए स्पष्ट और रेस्पॉन्सिव वेबसाइटें।", benefit: "एक पेशेवर डिजिटल उपस्थिति।" }, { id: "landing", title: "लैंडिंग पेज", shortTitle: "लैंडिंग पेज", subtitle: "विज़िटर को लीड और बिक्री में बदलें।", description: "अभियानों और कन्वर्ज़न पर केंद्रित पेज।", benefit: "हर विज़िटर के लिए स्पष्ट अगला कदम।" }, { id: "custom", title: "कस्टम वेब समाधान", shortTitle: "कस्टम वेब समाधान", subtitle: "आपके व्यवसाय के अनुसार बनाए गए टूल।", description: "आपके काम करने के तरीके के अनुरूप डिजिटल टूल।", benefit: "सरल और बेहतर व्यवस्थित प्रक्रियाएँ।" }, { id: "media", title: "इमेज, वीडियो और ऑडियो एडिटिंग", shortTitle: "मीडिया एडिटिंग", description: "उत्पादों, आयोजनों और डिजिटल कंटेंट के लिए पेशेवर एडिटिंग।", benefit: "सुसंगत विज़ुअल और ऑडियो संचार।" }, { id: "event", title: "इवेंट और QR वेबसाइटें", shortTitle: "इवेंट और QR वेबसाइटें", subtitle: "सरल अनुभव, जिन्हें लोग इस्तेमाल करना पसंद करें।", description: "मेहमानों और आयोजनों के लिए मोबाइल अनुभव।", benefit: "बिना ऐप के आसान भागीदारी।" }, { id: "agri", title: "कृषि व्यवसाय समाधान", shortTitle: "कृषि व्यवसाय समाधान", subtitle: "कृषि के लिए बनाए गए डिजिटल टूल।", description: "कृषि क्षेत्र के लिए वेबसाइटें और डिजिटल टूल।", benefit: "खेत और व्यवसाय के लिए उपयोगी तकनीक।" }, { id: "care", title: "वेबसाइट देखभाल और सहायता", shortTitle: "वेबसाइट देखभाल और सहायता", subtitle: "अपडेट, सुधार और निरंतर सहायता।", description: "वेबसाइट को विश्वसनीय और अद्यतन रखने के लिए देखभाल।", benefit: "लॉन्च के बाद भी निरंतर सहयोग।" }],
    portfolioSection: { eyebrow: "पोर्टफोलियो", title: "चुनिंदा प्रोजेक्ट।", description: "ऐसे काम जो स्पष्टता, अनुभव और परिणामों को साथ लाते हैं।", view: "प्रोजेक्ट देखें", videoDemo: "प्रोजेक्ट डेमो", screenshot: "प्रोजेक्ट का स्क्रीनशॉट" },
    projects: [{ name: "AgriClimate Pro", category: "वेब डेवलपमेंट · AgTech", description: "जलवायु डेटा से कृषि निर्णयों में मदद करने वाला डिजिटल अनुभव।" }, { name: "Frasson LLC", category: "वेब डेवलपमेंट", description: "सेवाएँ प्रस्तुत करने और संपर्क आसान बनाने के लिए तैयार स्पष्ट व्यावसायिक वेबसाइट।" }, { name: "Event QR Code", category: "आयोजनों के लिए डिजिटल अनुभव", description: "मेहमानों के लिए QR कोड से फ़ोटो और वीडियो भेजने का आसान तरीका।" }, { name: "Cafeteria", category: "वेब डेवलपमेंट · खाद्य एवं पेय", description: "कैफ़े के अनुभव को प्रस्तुत करने और मेन्यू तक आसान पहुँच देने वाली आकर्षक, रेस्पॉन्सिव वेबसाइट।" }, { name: "ऑटो रिपेयर शॉप", category: "वेब डेवलपमेंट · ऑटोमोटिव सेवाएँ", description: "वर्कशॉप की सेवाएँ प्रस्तुत करने और स्थानीय ग्राहकों के लिए संपर्क आसान बनाने वाली रेस्पॉन्सिव वेबसाइट।" }, { type: "collaboration", collection: "चयनित सहयोग · AI और डेटा", name: "अंतरराष्ट्रीय AI डेटा परियोजना", category: "AI प्रशिक्षण और डेटा संग्रह", description: "संरचित डेटा संग्रह, सत्यापन और गुणवत्ता-नियंत्रित डिलीवरी के माध्यम से बड़े पैमाने की AI प्रशिक्षण पहल में योगदान दिया।", tagsLabel: "सहयोग क्षमताएँ", tags: ["AI प्रशिक्षण डेटा", "डेटा संग्रह", "गुणवत्ता आश्वासन"], metrics: [{ value: "30+ घंटे", label: "संरचित डेटा वितरित" }] }],
    company: { eyebrow: "कंपनी", title: "इंसानों द्वारा निर्मित", description: "वास्तविक लोग, वास्तविक व्यावसायिक ज़रूरतों के लिए स्पष्ट और उपयोगी डिजिटल समाधान बनाते हैं।", localSeo: { text: "Mediatrix Tech सांता मारिया, रियो ग्रांडे डो सुल, ब्राज़ील के अन्य क्षेत्रों और दुनिया भर के व्यवसायों के लिए वेबसाइट और डिजिटल समाधान विकसित करता है।", link: "सांता मारिया, RS में वेबसाइट निर्माण" }, facts: [["मानवीय नेतृत्व", "वास्तविक लोग। सीधा संवाद।"], ["आपके अनुसार निर्मित", "आपके व्यवसाय के अनुरूप समाधान।"], ["स्पष्ट प्रक्रिया", "सरल संवाद। अनावश्यक जटिलता नहीं।"], ["दुनिया भर में", "व्यवसाय जहाँ भी हों, हम उनके साथ काम करते हैं।"]] },
    contact: { eyebrow: "संपर्क", title: "आइए आपके प्रोजेक्ट के बारे में बात करें।", description: "सबसे सुविधाजनक माध्यम चुनें या फ़ॉर्म से हमें संदेश भेजें।", channelsLabel: "संपर्क माध्यम", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["ईमेल", "mediatrixtech@proton.me"], ["Upwork प्रोफ़ाइल", "अंतरराष्ट्रीय प्रोजेक्ट"]], form: { title: "संदेश भेजें", description: "संक्षेप में बताएँ कि आपको क्या चाहिए।", name: "नाम", email: "ईमेल", service: "रुचि की सेवा", chooseService: "एक सेवा चुनें", message: "संदेश", send: "संदेश भेजें", sending: "भेजा जा रहा है...", success: "संदेश सफलतापूर्वक भेजा गया। हम जल्द संपर्क करेंगे।", error: "संदेश नहीं भेजा जा सका। दोबारा कोशिश करें या WhatsApp पर संपर्क करें।", subject: "Mediatrix Tech वेबसाइट से नया संदेश" } },
    rights: "सर्वाधिकार सुरक्षित।",
  },

  ar: {
    easterEggs: easterEggTranslations.ar,
    metaTitle: "مواقع احترافية وحلول رقمية | Mediatrix Tech",
    metaDescription: "تصمم Mediatrix Tech مواقع إلكترونية ومحتوى بصري احترافي للشركات حول العالم.",
    skip: "الانتقال إلى المحتوى", nav: ["الرئيسية", "الخدمات", "الأعمال", "الشركة", "التواصل"], primaryNavigation: "التنقل الرئيسي", mobileNavigation: "التنقل عبر الهاتف", language: "اللغة", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة", quote: "اطلب مراجعة مجانية لموقعك",
    hero: { logoAlt: "شعار Mediatrix Tech", title: "المزيد من العملاء. المزيد من الإيرادات. نمو في الإيرادات أسرع بنسبة تصل إلى 27%.*", footnote: "*استنادًا إلى بحث أجرته Deloitte Access Economics يقارن الشركات الصغيرة والمتوسطة ذات التفاعل الرقمي المتقدم بالشركات غير المتصلة بالإنترنت.", primaryCta: "اطلب مراجعة مجانية لموقعك", secondaryCta: "شاهد أعمالنا" },
    servicesSection: { eyebrow: "الخدمات", title: "ما الذي يمكننا بناؤه لك", description: "من أول موقع إلكتروني إلى أداة مخصصة، يبدأ كل مشروع بهدف واضح ونطاق محدد." },
    services: [{ id: "site", title: "مواقع احترافية", shortTitle: "مواقع احترافية", subtitle: "ابنِ الثقة. واجذب المزيد من العملاء.", description: "مواقع واضحة ومتجاوبة لتقديم نشاطك.", benefit: "حضور رقمي احترافي." }, { id: "landing", title: "صفحات هبوط", shortTitle: "صفحات هبوط", subtitle: "حوّل الزوار إلى عملاء محتملين ومبيعات.", description: "صفحات مركزة للحملات والتحويل.", benefit: "خطوة تالية واضحة لكل زائر." }, { id: "custom", title: "حلول ويب مخصصة", shortTitle: "حلول ويب مخصصة", subtitle: "أدوات مصممة حول احتياجات عملك.", description: "أدوات رقمية تتكيف مع طريقة عملك.", benefit: "عمليات أبسط وأكثر تنظيمًا." }, { id: "media", title: "تحرير الصور والفيديو والصوت", shortTitle: "تحرير الوسائط", description: "تحرير احترافي للمنتجات والفعاليات والمحتوى الرقمي.", benefit: "تواصل بصري وصوتي متسق." }, { id: "event", title: "مواقع الفعاليات ورموز QR", shortTitle: "مواقع الفعاليات ورموز QR", subtitle: "تجارب بسيطة يحب الناس استخدامها.", description: "تجارب للهواتف مصممة للضيوف والفعاليات.", benefit: "مشاركة سهلة من دون تطبيق." }, { id: "agri", title: "حلول الأعمال الزراعية", shortTitle: "حلول الأعمال الزراعية", subtitle: "أدوات رقمية مصممة للزراعة.", description: "مواقع وأدوات رقمية للقطاع الزراعي.", benefit: "تقنية مفيدة للميدان والعمل." }, { id: "care", title: "العناية بالموقع والدعم", shortTitle: "العناية بالموقع والدعم", subtitle: "تحديثات وتحسينات ودعم مستمر.", description: "عناية مستمرة للحفاظ على موثوقية موقعك وتحديثه.", benefit: "دعم متواصل بعد الإطلاق." }],
    portfolioSection: { eyebrow: "الأعمال", title: "مشاريع مختارة.", description: "أعمال تجمع بين الوضوح والخبرة والنتائج.", view: "عرض المشروع", videoDemo: "عرض توضيحي للمشروع", screenshot: "لقطة شاشة للمشروع" },
    projects: [{ name: "AgriClimate Pro", category: "تطوير المواقع · التقنية الزراعية", description: "تجربة رقمية تدعم القرارات الزراعية بالاعتماد على بيانات المناخ." }, { name: "Frasson LLC", category: "تطوير المواقع", description: "موقع أعمال واضح صُمم لعرض الخدمات وتسهيل التواصل." }, { name: "Event QR Code", category: "تجربة رقمية للفعاليات", description: "مسار بسيط عبر رمز QR يتيح للضيوف إرسال الصور والفيديوهات." }, { name: "Cafeteria", category: "تطوير المواقع · الأغذية والمشروبات", description: "موقع دافئ ومتجاوب يعرض تجربة المقهى ويسهّل الوصول إلى قائمة الطعام." }, { name: "ورشة صيانة السيارات", category: "تطوير المواقع · خدمات السيارات", description: "موقع متجاوب يعرض خدمات الورشة ويسهّل تواصل العملاء المحليين." }, { type: "collaboration", collection: "تعاون مختار · الذكاء الاصطناعي والبيانات", name: "مشروع دولي لبيانات الذكاء الاصطناعي", category: "تدريب الذكاء الاصطناعي وجمع البيانات", description: "ساهمنا في مبادرة واسعة النطاق لتدريب الذكاء الاصطناعي من خلال جمع البيانات المنظمة والتحقق منها وتسليمها وفق ضوابط الجودة.", tagsLabel: "قدرات التعاون", tags: ["بيانات تدريب الذكاء الاصطناعي", "جمع البيانات", "ضمان الجودة"], metrics: [{ value: "30+ ساعة", label: "بيانات منظمة تم تسليمها" }] }],
    company: { eyebrow: "الشركة", title: "صُنع بأيدٍ بشرية", description: "أشخاص حقيقيون يبنون حلولًا رقمية واضحة ومفيدة حول احتياجات الأعمال الحقيقية.", localSeo: { text: "تطوّر Mediatrix Tech مواقع وحلولًا رقمية للشركات في سانتا ماريا وريو غراندي دو سول ومناطق أخرى من البرازيل والعالم.", link: "إنشاء مواقع في سانتا ماريا، RS" }, facts: [["بقيادة بشرية", "أشخاص حقيقيون. تواصل مباشر."], ["مصمم من أجلك", "حلول تتشكل حول احتياجات عملك."], ["عملية واضحة", "تواصل بسيط. دون تعقيد غير ضروري."], ["حول العالم", "نعمل مع الشركات أينما كانت."]] },
    contact: { eyebrow: "التواصل", title: "لنتحدث عن مشروعك.", description: "اختر وسيلة التواصل الأنسب أو أرسل لنا رسالة عبر النموذج.", channelsLabel: "وسائل التواصل", channels: [["WhatsApp", "+1 305 992 0833"], ["WhatsApp", "+55 55 99935-7388"], ["البريد الإلكتروني", "mediatrixtech@proton.me"], ["حساب Upwork", "مشاريع دولية"]], form: { title: "إرسال رسالة", description: "أخبرنا بإيجاز بما تحتاج إليه.", name: "الاسم", email: "البريد الإلكتروني", service: "الخدمة المطلوبة", chooseService: "اختر خدمة", message: "الرسالة", send: "إرسال الرسالة", sending: "جارٍ الإرسال...", success: "تم إرسال رسالتك بنجاح. سنتواصل معك قريبًا.", error: "تعذر إرسال الرسالة. حاول مرة أخرى أو تواصل معنا عبر WhatsApp.", subject: "رسالة جديدة من موقع Mediatrix Tech" } },
    rights: "جميع الحقوق محفوظة.",
  },
};

function mergeWithEnglishFallback(englishValue, localizedValue) {
  if (!englishValue || typeof englishValue !== "object" || Array.isArray(englishValue)) {
    return localizedValue ?? englishValue;
  }

  return Object.fromEntries(
    Object.keys(englishValue).map((key) => [
      key,
      mergeWithEnglishFallback(englishValue[key], localizedValue?.[key]),
    ]),
  );
}

export function getEasterEggCopy(locale) {
  return mergeWithEnglishFallback(
    translations.en.easterEggs,
    translations[locale]?.easterEggs,
  );
}
